# Generated by Django 4.2.23 on 2025-07-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tripparticipant',
            table='trip_participant',
        ),
    ]
