# Generated by Django 4.2.23 on 2025-07-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tripparticipant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tripparticipant',
            table='api_trip_participant',
        ),
    ]
