# Generated by Django 4.2.23 on 2025-07-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating_received',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reviews_given',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_reviews_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_trips_joined',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trips_cancelled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trips_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
