# Generated by Django 4.2.23 on 2025-07-19 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_is_staff_trip_likes_tripinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_trip_comment',
            },
        ),
        migrations.CreateModel(
            name='TripLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_trip_like',
                'unique_together': {('trip', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='TripInteraction',
        ),
    ]
