# Generated by Django 4.2.23 on 2025-07-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tripcomment_triplike_delete_tripinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
